using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace MERAS.Models
{
	public class Department
    {
		//  Specifies that the PK is provided by the application rather than generated by the database.
		[DatabaseGenerated(DatabaseGeneratedOption.None)]
		[Display(Name = "Department ID")]
		[StringLength(2)]
		public string ID { get; set; }

		[Required]
		[StringLength(45, ErrorMessage = "First name cannot be longer than 45 characters.")]
		[Display(Name = "Department Name")]
		public string Name { get; set; }
	}
}
